name: Apollo

channels:
  - conda-forge
  
dependencies:
  - python=3.7
  - pandas
  - matplotlib
  - jupyterlab
  - seaborn
  - lxml
  - xmltodict
  - beautifulsoup4
  - html5lib
  - python-dotenv
  - pip
  
  - pip:
      - ipypb
      - feautils
