name: Update data

on:
  push:
  schedule:
  - cron: "45 9 * * 1-5"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas
        python -m pip install requests
        python -m pip install lxml
        python -m pip install ipython
        python -m pip install FEAutils
        python -m pip install python-dotenv
        
    - name: Updating data
      run: |
        python update_data.py
      
    - uses: stefanzweifel/git-auto-commit-action@v4 
